"""initial_schema

Revision ID: 1346c3c9c55e
Revises: 
Create Date: 2026-01-20 02:56:14.813289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1346c3c9c55e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_text', sa.Text(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('meeting_title', sa.String(length=255), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('total_confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priorityenum'), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevelenum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clarification_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_item_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_item_id', sa.String(length=36), nullable=False),
    sa.Column('risk_type', sa.Enum('VAGUE_DESCRIPTION', 'MISSING_OWNER', 'MISSING_DEADLINE', 'UNCLEAR_DEPENDENCY', 'SCOPE_TOO_BROAD', 'CONFLICTING_ASSIGNMENT', name='risktypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priorityenum'), nullable=False),
    sa.Column('suggested_clarification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_flags')
    op.drop_table('clarification_questions')
    op.drop_table('action_items')
    op.drop_table('meetings')
    # ### end Alembic commands ###
